language: go

go:
  - 1.15.x

branches:
  only:
    - master

before_install:
  - go get -t -v ./...

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)